# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

after_success:
  - curl -sSL "https://raw.githubusercontent.com/h5bp-bot/scripts/master/update_server_branch.sh" |
      bash /dev/stdin "server-content" "Hey server, this content is for you!"

before_script:
  - travis_retry npm install -g grunt-cli

branches:
  except:
    - server-content

env:
  global:
    - secure: "FpwKgXOGYIAh6LuRWfbX4ezFpIynoEa0kR2zvXMBYgXJzE9DLuavcXkJF8FPGeDmveSCXFdS6QPNhgyQB4fzDG625CdFYxpObJMgRBDoO71LYSpr6NPSsS6n82KU+1gisG1FPqXCGKd9yDekIHNb+AosCbhYEeLfq4yFSaE/J2g="

git:
  depth: 10

language: node_js

node_js:
  - "0.10"
